import * as api from './api/api';
import * as angular from 'angular';

const services = angular.module('api', [])
.service('AccountApi', api.AccountApi)
.service('AccountApiMock', api.AccountApiMock)
.service('CategoryApi', api.CategoryApi)
.service('CategoryApiMock', api.CategoryApiMock)
.service('ConfigApi', api.ConfigApi)
.service('ConfigApiMock', api.ConfigApiMock)
.service('DefaultApi', api.DefaultApi)
.service('DefaultApiMock', api.DefaultApiMock)
.service('EmploymentApi', api.EmploymentApi)
.service('EmploymentApiMock', api.EmploymentApiMock)
.service('FilesApi', api.FilesApi)
.service('FilesApiMock', api.FilesApiMock)
.service('FinancesApi', api.FinancesApi)
.service('FinancesApiMock', api.FinancesApiMock)
.service('MsisdnApi', api.MsisdnApi)
.service('MsisdnApiMock', api.MsisdnApiMock)
.service('PaymentsApi', api.PaymentsApi)
.service('PaymentsApiMock', api.PaymentsApiMock)
.service('PayoutsApi', api.PayoutsApi)
.service('PayoutsApiMock', api.PayoutsApiMock)
.service('ProfileApi', api.ProfileApi)
.service('ProfileApiMock', api.ProfileApiMock)
.service('RatelApi', api.RatelApi)
.service('RatelApiMock', api.RatelApiMock)
.service('RecoverPasswordApi', api.RecoverPasswordApi)
.service('RecoverPasswordApiMock', api.RecoverPasswordApiMock)
.service('RegistrationApi', api.RegistrationApi)
.service('RegistrationApiMock', api.RegistrationApiMock)
.service('SearchApi', api.SearchApi)
.service('SearchApiMock', api.SearchApiMock)
.service('ServiceApi', api.ServiceApi)
.service('ServiceApiMock', api.ServiceApiMock)
.service('SessionApi', api.SessionApi)
.service('SessionApiMock', api.SessionApiMock)
.service('TagApi', api.TagApi)
.service('TagApiMock', api.TagApiMock)
.service('ViewsApi', api.ViewsApi)
.service('ViewsApiMock', api.ViewsApiMock)
.service('WsApi', api.WsApi)
.service('WsApiMock', api.WsApiMock)

const apiModule = services.name;

export default apiModule;
