stages:
  - test-prepare-code
  - test-run
  - build-push-release-image
  - release-deploy

variables:
  # Update from $CI_COMMIT_SHA to $CI_PIPELINE_IID when gitlab > v.11
  CONTAINER_TEST_IMAGE_URL: eu.gcr.io/dev-country-188109/profitelo-frontend:test-$CI_COMMIT_SHA
  CONTAINER_RELEASE_IMAGE_URL: eu.gcr.io/dev-country-188109/profitelo-frontend:dev-$CI_COMMIT_SHA

test-prepare-code:
  stage: test-prepare-code
  except:
    - develop
  script:
    - docker build --no-cache -t $CONTAINER_TEST_IMAGE_URL -f Dockerfile.test .
  tags:
    - shell

test-run:
  stage: test-run
  except:
    - develop
  script:
    - docker run -i $CONTAINER_TEST_IMAGE_URL /bin/sh -c 'npm install && npm run ci-test' && docker rmi -f $CONTAINER_TEST_IMAGE_URL
  tags:
    - shell


build-push-release-image:
  stage: build-push-release-image
  script:
    - docker build --no-cache -t $CONTAINER_RELEASE_IMAGE_URL -f Dockerfile.build .
    - docker push $CONTAINER_RELEASE_IMAGE_URL
  only:
    - develop
  after_script:
    - docker rm $CONTAINER_RELEASE_IMAGE_URL
  tags:
    - shell

release-deploy:
  stage: release-deploy
  before_script:
    - mkdir -p /opt/anymind/deploy
    - helm init --service-account default
    - git clone git@git.contactis.pl:itelo/anymind-deployment.git /opt/anymind/deploy
  script:
    - cd /opt/anymind/deploy/
    - helm del --purge am-dev-frontend
    - helm install --wait --name am-dev-frontend am-frontend/helm/ -f am-frontend/helm/values-dev.yaml --set image.repository=eu.gcr.io/dev-country-188109/profitelo-frontend,image.tag=dev-$CI_COMMIT_SHA
  only:
    - develop
  tags:
    - deathstar-anymind-helm-0
