stages:
  - test-prepare-code
  - test-run
  - build-push-release-image
  - deploy

variables:
  CONTAINER_TEST_IMAGE_URL: eu.gcr.io/dev-country-188109/profitelo-frontend:test-$CI_PIPELINE_IID
  CONTAINER_RELEASE_IMAGE_URL: eu.gcr.io/dev-country-188109/profitelo-frontend:release-$CI_COMMIT_SHA

test-prepare-code:
  stage: test-prepare-code
  except:
    - master
  script:
    - docker build --no-cache -t $CONTAINER_TEST_IMAGE_URL -f gitlab-ci/Dockerfile.test .
  tags:
    - shell

test-run:
  stage: test-run
  except:
    - master
  script:
    - docker run -i $CONTAINER_TEST_IMAGE_URL /bin/sh -c 'npm install && npm run ci-test' && docker rmi -f $CONTAINER_TEST_IMAGE_URL
  tags:
    - shell


build-push-release-image:
  stage: build-push-release-image
  script:
    - docker build --no-cache -t $CONTAINER_RELEASE_IMAGE_URL -f gitlab-ci/Dockerfile.build .
    - docker push $CONTAINER_RELEASE_IMAGE_URL
  only:
    - master
  after_script:
    - docker rm $CONTAINER_RELEASE_IMAGE_URL
  tags:
    - shell

deploy-dev:
  stage: deploy
  environment:
    name: development
    url: https://dev.anymind.com
  before_script:
    - kubectl config use-context admin-cluster.local
    - helm init --service-account default
    - cd gitlab-ci
  script:
    - helm del --purge am-dev-frontend
    - helm install --wait --name am-dev-frontend helm/ -f helm/values-dev.yaml --set image.repository=eu.gcr.io/dev-country-188109/profitelo-frontend,image.tag=release-$CI_COMMIT_SHA
  only:
    - master
  tags:
    - deathstar-anymind-helm-0
