stages:
  - test
  - build-release
  - deploy-release

variables:
  CONTAINER_TEST_IMAGE: profitelo-frontend:test-$CI_PIPELINE_IID
  CONTAINER_RELEASE_IMAGE_URL: eu.gcr.io/dev-country-188109/profitelo-frontend:release-$CI_COMMIT_SHA

test:
  stage: test
  except:
    - master
  script:
    - docker build --no-cache -t $CONTAINER_TEST_IMAGE -f gitlab-ci/Dockerfile.test .
    - docker run -v=/opt/anymind/npm:/home/chrome/.npm $CONTAINER_TEST_IMAGE
  after_script:
    - docker rmi -f $CONTAINER_TEST_IMAGE
  tags:
    - shell


build-release:
  stage: build-release
  script:
    - docker build --no-cache -t $CONTAINER_RELEASE_IMAGE_URL -f gitlab-ci/Dockerfile.build .
    - docker push $CONTAINER_RELEASE_IMAGE_URL
  only:
    - master
  after_script:
    - docker rmi -f $CONTAINER_RELEASE_IMAGE_URL
  tags:
    - shell

stage-deploy:
  stage: deploy-release
  environment:
    name: staging
    url: https://stage.anymind.com
  before_script:
    - kubectl config use-context gke_dev-country-188109_europe-west3-b_anymind-stage-eu
    - helm init --service-account default
    - cd gitlab-ci
  script:
    - helm del --purge am-stage-frontend
    - helm install --wait --name am-stage-frontend helm/ -f helm/values-stage.yaml --set image.repository=eu.gcr.io/dev-country-188109/profitelo-frontend,image.tag=release-$CI_COMMIT_SHA
  only:
    - master
  tags:
    - deathstar-anymind-helm-0

demo-deploy:
  stage: deploy-release
  environment:
    name: demo
    url: https://demo.anymind.com
  before_script:
    - kubectl config use-context gke_dev-country-188109_europe-west2-b_anymind-demo-eu
    - helm init --service-account default
    - cd gitlab-ci
  script:
    - helm del --purge am-frontend || true
    - helm install --wait --name am-frontend helm/ -f helm/values-demo.yaml --set image.repository=eu.gcr.io/dev-country-188109/profitelo-frontend,image.tag=release-$CI_COMMIT_SHA
  only:
    - master
  when: manual
  tags:
    - deathstar-anymind-helm-0

prod-deploy:
  stage: deploy-release
  environment:
    name: production
    url: https://app.anymind.com
  before_script:
    - kubectl config use-context gke_dev-country-188109_europe-west2-a_anymind-prod-eu
    - helm init --service-account default
    - cd gitlab-ci
  script:
    - helm del --purge am-frontend || true
    - helm install --wait --name am-frontend helm/ -f helm/values-prod.yaml --set image.repository=eu.gcr.io/dev-country-188109/profitelo-frontend,image.tag=release-$CI_COMMIT_SHA
  only:
    - master
  when: manual
  tags:
    - deathstar-anymind-helm-0
