FROM eu.gcr.io/dev-country-188109/ubuntu-node-base-test:10.4.1
MAINTAINER loord igor.gerasimow@ratel.io

#name of app branch
ARG branch=develop

#name of common-config branch
ARG common=master

# build env
ARG env=build-dev

RUN git clone git@git.contactis.pl:itelo/profitelo-frontend.git /home/chrome/profitelo-frontend -b $branch

WORKDIR /home/chrome/profitelo-frontend

ENV PROFITELO_ENV=build-dev

RUN npm install && git submodule update --init --recursive