FROM eu.gcr.io/dev-country-188109/ubuntu-node-base-test:10.4.1
MAINTAINER loord igor.gerasimow@ratel.io

# prepare dir for cache
RUN mkdir /home/chrome/.npm

ADD . /home/chrome/profitelo-frontend

USER root
RUN chown chrome -R /home/chrome/profitelo-frontend
USER chrome

WORKDIR /home/chrome/profitelo-frontend

RUN git submodule update --init --recursive
