export * from './AccountApi';
import { AccountApi }  from './AccountApi';
export * from './CategoryApi';
import { CategoryApi }  from './CategoryApi';
export * from './ConfigApi';
import { ConfigApi }  from './ConfigApi';
export * from './DefaultApi';
import { DefaultApi }  from './DefaultApi';
export * from './EmploymentApi';
import { EmploymentApi }  from './EmploymentApi';
export * from './FilesApi';
import { FilesApi }  from './FilesApi';
export * from './FinancesApi';
import { FinancesApi }  from './FinancesApi';
export * from './MsisdnApi';
import { MsisdnApi }  from './MsisdnApi';
export * from './PaymentsApi';
import { PaymentsApi }  from './PaymentsApi';
export * from './PayoutsApi';
import { PayoutsApi }  from './PayoutsApi';
export * from './ProfileApi';
import { ProfileApi }  from './ProfileApi';
export * from './RatelApi';
import { RatelApi }  from './RatelApi';
export * from './RecoverPasswordApi';
import { RecoverPasswordApi }  from './RecoverPasswordApi';
export * from './RegistrationApi';
import { RegistrationApi }  from './RegistrationApi';
export * from './SearchApi';
import { SearchApi }  from './SearchApi';
export * from './ServiceApi';
import { ServiceApi }  from './ServiceApi';
export * from './SessionApi';
import { SessionApi }  from './SessionApi';
export * from './TagApi';
import { TagApi }  from './TagApi';
export * from './ViewsApi';
import { ViewsApi }  from './ViewsApi';
export * from './WsApi';
import { WsApi }  from './WsApi';
export const APIS = [ AccountApi, CategoryApi, ConfigApi, DefaultApi, EmploymentApi, FilesApi, FinancesApi, MsisdnApi, PaymentsApi, PayoutsApi, ProfileApi, RatelApi, RecoverPasswordApi, RegistrationApi, SearchApi, ServiceApi, SessionApi, TagApi, ViewsApi, WsApi, ];
