FROM phusion/baseimage
MAINTAINER Mariusz Bełtowski <mariusz.beltowski@itelo.pl>

# install node

RUN apt-get update && apt-get install -y build-essential curl git python
RUN curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
RUN apt-get install -y nodejs

# install phantomjs requirements
RUN apt-get install -y libfreetype6 libfontconfig


# install gulp

RUN npm install -g gulp
RUN npm cache clean -f

# run
WORKDIR /
RUN mkdir /profitelo-frontend
ADD .git /profitelo-frontend/.git
ADD .npmrc /profitelo-frontend/.npmrc
ADD src /profitelo-frontend/src
ADD .eslintrc /profitelo-frontend/
ADD build.config.js /profitelo-frontend/
ADD gulpfile.js /profitelo-frontend/
ADD package.json /profitelo-frontend/
WORKDIR /profitelo-frontend

RUN npm prune
RUN npm install


WORKDIR /profitelo-frontend

ENTRYPOINT ["gulp", "build", "--no-wait"]
