#
# Profitelo frontend development image
#
# Version: 0.0.1
#

FROM dockerhub.contactis.pl/node
MAINTAINER Jarosław Płocki <jaroslaw.plocki@itelo.pl>

RUN mkdir /profitelo-frontend

ADD package.json /profitelo-frontend/
ADD .npmrc /profitelo-frontend/

WORKDIR /profitelo-frontend

RUN npm install

ADD . /profitelo-frontend

ADD docker/nginx.conf /etc/nginx/sites-enabled/default
ADD docker/init_scripts/nginx.sh /etc/service/nginx/run
ADD docker/init_scripts/frontend.sh /etc/service/frontend/run

CMD ["/sbin/my_init", "--enable-insecure-key"]
