FROM dockerhub.contactis.pl/node
MAINTAINER Mariusz Bełtowski <mariusz.beltowski@itelo.pl>

RUN mkdir /profitelo-frontend
WORKDIR /profitelo-frontend

ADD package.json /profitelo-frontend/
ADD .npmrc /profitelo-frontend/
RUN npm install

ADD . /profitelo-frontend/

RUN ln -s phantomjs-prebuilt node_modules/phantomjs

CMD gulp build
