/**
 * Profitelo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

models;

export interface AccountDetails {
    "unverifiedEmail"?: string;
    "permissions": Array<models.Permission>;
    "currency": string;
    "settings": models.AccountSettings;
    "status": models.AccountStatus;
    "hasMobilePin": boolean;
    "msisdn": string;
    "id": string;
    "deletedAt"?: Date;
    "email"?: string;
    "registeredAt": number;
    "defaultCreditCard"?: string;
    "protectedViews": Array<string>;
    "hasPassword": boolean;
    "isBlocked": boolean;
    "isCompany": boolean;
    "doesMsisdnMatchCountry": boolean;
    "countryISO": string;
}

