/**
 * Profitelo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * AddAccount
 */
export interface AddAccount {
    "telcoPin": string;
    "msisdn": string;
    "deletedAt": Date;
    "email"?: string;
    "password"?: string;
    "currency": string;
    "status": models.AccountStatus;
    "isCompany": boolean;
    "isBlocked": boolean;
    "countryISO": string;
}

