/**
 * Profitelo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface FileInfo {
    "isUploaded": boolean;
    "downloadUrl"?: string;
    "id"?: string;
    "contentType": string;
    "persisted"?: boolean;
    "previews": Array<string>;
    "createdAt": Date;
    "name"?: string;
    "collectionType": FileInfo.CollectionTypeEnum;
    "status": FileInfo.StatusEnum;
    "token": string;
    "accountId": string;
    "size"?: number;
}

export namespace FileInfo {
    export enum CollectionTypeEnum {
        COVER = <any> 'COVER',
        AVATAR = <any> 'AVATAR',
        DOCUMENT = <any> 'DOCUMENT',
        FILM = <any> 'FILM',
        GALLERY = <any> 'GALLERY'
    }
    export enum StatusEnum {
        NEW = <any> 'NEW',
        ACCEPTED = <any> 'ACCEPTED',
        REJECTED = <any> 'REJECTED'
    }
}
