/**
 * Profitelo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

models;

export interface FinancialOperation {
    "type": FinancialOperation.TypeEnum;
    "createdAt": Date;
    "accountType": FinancialOperation.AccountTypeEnum;
    "operation": models.MoneyDto;
    "id": string;
    "balanceAfter": models.MoneyDto;
    "persisted"?: boolean;
    "accountId": string;
}

export namespace FinancialOperation {
    export enum TypeEnum {
        SERVICEUSAGECLIENT = <any> 'SERVICE_USAGE_CLIENT',
        PAYMENT = <any> 'PAYMENT',
        REFUNDCLIENT = <any> 'REFUND_CLIENT',
        SERVICEUSAGEEXPERT = <any> 'SERVICE_USAGE_EXPERT',
        PAYOUT = <any> 'PAYOUT',
        REFUNDEXPERT = <any> 'REFUND_EXPERT'
    }
    export enum AccountTypeEnum {
        CLIENT = <any> 'CLIENT',
        PROFILE = <any> 'PROFILE'
    }
}
