/**
 * Profitelo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface GetServiceUsageDetails {
    "callDuration": number;
    "ratelCallId": string;
    "ratePerMinute": models.MoneyDto;
    "callCost": models.MoneyDto;
    "startedAt": Date;
    "serviceUsageEventId": string;
}

