/**
 * Profitelo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ServiceUsageEvent {
    "freeSeconds": number;
    "ratelCallId": string;
    "clientId": string;
    "id"?: string;
    "persisted"?: boolean;
    "serviceId": string;
    "clientFinancialOperationId"?: string;
    "createdAt": Date;
    "startedAt"?: Date;
    "ratePerMinute": models.MoneyDto;
    "stoppedAt"?: Date;
    "expertId": string;
    "expertFinancialOperationId"?: string;
    "callSignificant"?: boolean;
}

