replicaCount: 1

image:
  repository: eu.gcr.io/dev-country-188109/profitelo-frontend
  tag: prod
  pullPolicy: Always

service:
  name: frontend
  type: LoadBalancer
  loadBalancerIP: 35.198.82.21
  ports:
    http: 80
    https: 443

resources: {}

frontend:
  DEPLOY_TYPE: prod
  LOG_TAG: prod
  LOGSTASH_URL: logstash:5000
  PROFITELO_ENV: build-prod
  WIDGET_ENV: build-prod