import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'plat-content-loader',
  templateUrl: 'content-loader.component.html',
})
export class ContentLoaderComponent implements OnInit {
  @Input()
  public width = 400;
  @Input()
  public height = 130;
  @Input()
  public speed = 2;
  @Input()
  public color = '#dfe0e1';
  @Input()
  public primaryOpacity = 1;
  @Input()
  public secondaryOpacity = 0.35;

  public gradientId = this.generateId();
  public clipId = this.generateId();
  public gradientX2: string;
  public gradientY2: string;
  public attrToAnimate: 'x' | 'y';
  public orientation: 'portrait' | 'landscape';

  private readonly hundred = 100;

  public ngOnInit(): void {
    const ratio = `${(this.hundred / Math.max(this.width, this.height)) * Math.min(this.width, this.height)}%`;
    if (this.width > this.height) {
      this.orientation = 'landscape';
      this.gradientX2 = '100%';
      this.gradientY2 = ratio;
      this.attrToAnimate = 'x';
    } else {
      this.orientation = 'portrait';
      this.gradientY2 = '100%';
      this.gradientX2 = ratio;
      this.attrToAnimate = 'y';
    }
  }

  public get fillStyle(): { fill: string } {
    return {
      fill: `url(${window.location.href}#${this.gradientId})`,
    };
  }

  public get clipStyle(): string {
    return `url(${window.location.href}#${this.clipId})`;
  }

  /**
   * generate unique id based on random number
   * result is like hash example: bib7v739bkg
   * it will be duped if the same value will be generated by random
   */
  private generateId(): string {
    // tslint:disable:no-magic-numbers
    return Math.random()
      .toString(32)
      .substring(2);
  }
}
