import { Component, ElementRef, Input, OnInit, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'plat-content-loader',
  templateUrl: './content-loader.component.html',
  styleUrls: ['./content-loader.component.sass'],
  encapsulation: ViewEncapsulation.None,
})
export class ContentLoaderComponent implements OnInit {
  @Input()
  public speed = 2;
  @Input()
  public color = '#dfe0e1';
  @Input()
  public primaryOpacity = 1;
  @Input()
  public secondaryOpacity = 0.35;

  public gradientId = this.generateId();
  public clipId = this.generateId();
  public gradientX2: string;
  public gradientY2: string;
  public attrToAnimate: 'x' | 'y';
  public orientation: 'portrait' | 'landscape';
  private readonly hundred = 100;

  constructor(private element: ElementRef) {}

  public ngOnInit(): void {
    this.calculateAttrSvgGradientAnimation({
      width: this.element.nativeElement.clientWidth,
      height: this.element.nativeElement.clientHeight,
    });
  }

  public get fillStyle(): { fill: string } {
    return {
      fill: `url(${window.location.href}#${this.gradientId})`,
    };
  }

  public get clipStyle(): string {
    return `url(${window.location.href}#${this.clipId})`;
  }

  private calculateAttrSvgGradientAnimation(sizes: IContentLoaderSize): void {
    const rectSidesRatio = `${(this.hundred / Math.max(sizes.width, sizes.height)) *
      Math.min(sizes.width, sizes.height)}%`;

    if (sizes.width > sizes.height) {
      this.orientation = 'landscape';
      this.gradientX2 = '100%';
      this.gradientY2 = rectSidesRatio;
      this.attrToAnimate = 'x';
    } else {
      this.orientation = 'portrait';
      this.gradientY2 = '100%';
      this.gradientX2 = rectSidesRatio;
      this.attrToAnimate = 'y';
    }
  }

  /**
   * generate unique id based on random number
   * result is like hash example: bib7v739bkg
   * it will be duped if the same value will be generated by random
   */
  private generateId(): string {
    // tslint:disable:no-magic-numbers
    return Math.random()
      .toString(32)
      .substring(2);
  }
}

export interface IContentLoaderSize {
  width: number;
  height: number;
}
