FROM eu.gcr.io/dev-country-188109/ubuntu-node-base-test:10.4.1 AS build-env
MAINTAINER loord igor.gerasimow@ratel.io

ADD . /project
WORKDIR /project
USER root
RUN npm install && npm run ci-deploy


## Dist lightweight container ##
FROM nginx:alpine
COPY --from=build-env /project/dist /dist

ENTRYPOINT ["nginx", "-g", "daemon off;"]
