FROM eu.gcr.io/dev-country-188109/profitelo-nginx:base
MAINTAINER loord igor.gerasimow@ratel.io

ADD . /project

WORKDIR /project

RUN npm install && npm run ci-deploy

RUN mv /project/dist /dist

RUN rm -rf /project

RUN chown -R nginx:nginx /dist

ENTRYPOINT ["nginx", "-g", "daemon off;"]
